apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hometask-prod
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: prod
    server: 'https://kubernetes.default.svc'
  source:
    path: k8/helm
    repoURL: 'https://github.com/Brylov/HomeTask'
    targetRevision: HEAD
    helm:
      valueFiles: 
        - prod-values.yaml
  project: default
  syncPolicy:
    automated:
      selfHeal: true