env: prod
php:
  name: hometask-php-prod
  image:
    registry: 587447957359.dkr.ecr.us-east-1.amazonaws.com
    repository: hometask
    tag: 1.0.49
  imagepullsecret: us-east-1-ecr-registry
  service:
    type: ClusterIP
    port: 9000
nginx:
  name: hometask-nginx-prod
  config: hometask-nginx-cm-prod
  image:
    registry: 587447957359.dkr.ecr.us-east-1.amazonaws.com
    repository: hometask-nginx
    tag: 1.0.49
  imagepullsecret: us-east-1-ecr-registry
  service:
    type: LoadBalancer
    port: 80
