env: dev
php:
  name: hometask-php-dev
  image:
    registry: 587447957359.dkr.ecr.us-east-1.amazonaws.com
    repository: hometask
    tag: 1.0.47
  imagepullsecret: us-east-1-ecr-registry
  service:
    type: ClusterIP
    port: 9000
nginx:
  name: hometask-nginx-dev
  image:
    registry: 587447957359.dkr.ecr.us-east-1.amazonaws.com
    repository: hometask-nginx
    tag: 1.0.47
  imagepullsecret: us-east-1-ecr-registry
  service:
    type: LoadBalancer
    port: 80
