version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./nginx.conf:/etc/nginx
    ports:
      - "8081:80"
    networks: 
      - jenkins_nw
    depends_on:
      - php

  php:
    build:
      context: ./app
    networks: 
      - jenkins_nw

networks:
  jenkins_nw:
    external: true 

  
