version: '2'
services:
  nginx:
    image: nginx:1.11.8-alpine
    volumes:
      - ./index.php:/var/www/html/index.php
      #- ./util:/etc/nginx
      - ./util/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    networks: 
      - jenkins_nw
    depends_on:
      - php

  php:
    build:
      context: ./app
    networks: 
      - jenkins_nw

networks:
  jenkins_nw:
    external: true 

  
