version: '2'
services:
  nginx:
    image: hometask-nginx
    volumes:
      - ./index.php:/var/www/html/index.php
    ports:
      - "8081:80"
    networks: 
      - jenkins_nw
    depends_on:
      - php

  php:
    image: hometask
    networks: 
      - jenkins_nw

networks:
  jenkins_nw:
    external: true 

  
