apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.nginx.name }}-{{ .Values.env }}
  name: {{ .Values.nginx.name }}-{{ .Values.env }}
spec:
  ports:
    - name: "http"
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.nginx.name }}-{{ .Values.env }}
  type: {{ .Values.nginx.service.type }}