apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: {{ .Values.nginx.config }}
{{ if eq .Values.env "dev" }}
data:  
  nginx.conf: |
    events {}

    http {
      include /etc/nginx/mime.types;
      include /etc/nginx/sites-enabled/*;
      
      server {
      
        listen 80;
        root /var/www/html;
        
        location = / {
          index index.php index.html index.htm;
          try_files $uri /index.php;	
        }

        location ~* \.php$ {
          fastcgi_pass hometask-php-dev:9000;
          #fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
        }
      }
    }
{{ else }}
data:  
  nginx.conf: |
    events {}

    http {
      include /etc/nginx/mime.types;
      include /etc/nginx/sites-enabled/*;
      
      server {
      
        listen 80;
        root /var/www/html;
        
        location = / {
          index index.php index.html index.htm;
          try_files $uri /index.php;	
        }

        location ~* \.php$ {
          fastcgi_pass hometask-php-prod:9000;
          #fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
        }
      }
    }
{{ end }}