apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.nginx.name }}
  name: {{ .Values.nginx.name }}
  namespace: {{ .Values.env }}
spec:
  ports:
    - name: "http"
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.nginx.name }}
  type: {{ .Values.nginx.service.type }}