apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service
  name: nginx-service
spec:
  ports:
    - name: "nginx"
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: hometask-nginx
  type: NodePort