apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-service
  name: php-service
spec:
  ports:
    - name: "http"
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: hometask-php
  type: ClusterIP